#!/usr/bin/env python3
"""Generate deploy/yt-dlp-requirements.txt for a given yt-dlp release.

The lock uses the dependency set that yt-dlp itself publishes and tests as its
``pin`` extra, evaluated for the production image (CPython 3.11 on Debian
bookworm, linux/amd64 and linux/arm64). Every pinned distribution is listed with
the sha256 of each wheel usable on those targets, so the Dockerfile can install
with ``pip --require-hashes --only-binary=:all:``.

Usage: python3 .github/scripts/yt-dlp-lock.py <yt-dlp-version> [output-path]
Only the Python standard library (plus pip's vendored ``packaging``) is used.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request

try:
    from packaging.markers import Marker
    from packaging.requirements import Requirement
except ImportError:  # pragma: no cover - fallback for runners without packaging
    from pip._vendor.packaging.markers import Marker  # type: ignore
    from pip._vendor.packaging.requirements import Requirement  # type: ignore

TARGET_ENV = {
    "implementation_name": "cpython",
    "implementation_version": "3.11.2",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_release": "",
    "platform_system": "Linux",
    "platform_version": "",
    "python_full_version": "3.11.2",
    "python_version": "3.11",
    "sys_platform": "linux",
}
ARCHES = ("x86_64", "aarch64")
VERSION_RE = re.compile(r"^[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}(\.[0-9]+)?$")


def pypi(name: str, version: str) -> dict:
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as response:  # noqa: S310 - fixed https host
        return json.load(response)


def usable_wheel(filename: str, arch: str) -> bool:
    if not filename.endswith(".whl"):
        return False
    tags = filename[:-4].split("-")[-3:]
    python_tag, abi_tag, platform_tag = tags
    pythons = python_tag.split(".")
    platforms = platform_tag.split(".")
    if platform_tag == "any":
        return any(p in ("py3", "py2.py3") or p.startswith("py3") for p in pythons) or "cp311" in pythons
    if not any(p.startswith("manylinux") and p.endswith(arch) for p in platforms):
        return False
    if abi_tag == "abi3":
        return any(re.fullmatch(r"cp3([0-9]+)", p) and int(p[3:]) <= 11 for p in pythons)
    return "cp311" in pythons and abi_tag == "cp311"


def hashes_for(name: str, version: str) -> list[str]:
    files = pypi(name, version)["urls"]
    selected: set[str] = set()
    for arch in ARCHES:
        matches = [f for f in files if not f.get("yanked") and usable_wheel(f["filename"], arch)]
        if not matches:
            raise SystemExit(f"{name}=={version}: no usable wheel for linux/{arch} cp311")
        selected.update(f["digests"]["sha256"] for f in matches)
    return sorted(selected)


def main() -> None:
    if len(sys.argv) not in (2, 3) or not VERSION_RE.match(sys.argv[1]):
        raise SystemExit("usage: yt-dlp-lock.py <yt-dlp-version> [output]")
    version = sys.argv[1]
    output = sys.argv[2] if len(sys.argv) == 3 else "deploy/yt-dlp-requirements.txt"

    # PyPI normalises 2026.08.19 to 2026.8.19; the release tag keeps the padding.
    pypi_version = ".".join(str(int(part)) for part in version.split("."))
    meta = pypi("yt-dlp", pypi_version)
    pins: dict[str, str] = {}
    for raw in meta["info"].get("requires_dist") or []:
        requirement = Requirement(raw)
        if requirement.marker is None:
            continue
        if not Marker(str(requirement.marker)).evaluate({**TARGET_ENV, "extra": "pin"}):
            continue
        if Marker(str(requirement.marker)).evaluate({**TARGET_ENV, "extra": ""}):
            continue
        specs = list(requirement.specifier)
        if len(specs) != 1 or specs[0].operator != "==":
            raise SystemExit(f"unexpected pin specifier: {raw}")
        pins[requirement.name.lower()] = specs[0].version

    if not pins:
        raise SystemExit("yt-dlp does not publish a 'pin' extra for this release")

    lines = [
        "# Generated by .github/scripts/yt-dlp-lock.py - do not edit by hand.",
        f"# yt-dlp {version} with the dependency set yt-dlp publishes as its 'pin' extra,",
        "# hashed for CPython 3.11 wheels on linux/amd64 and linux/arm64.",
    ]
    entries = [(f"yt-dlp[default]=={version}", "yt-dlp", pypi_version)]
    entries += [(f"{name}=={pin}", name, pin) for name, pin in sorted(pins.items())]
    for spec, name, pin in entries:
        digests = hashes_for(name, pin)
        lines.append(spec + " \\")
        for index, digest in enumerate(digests):
            suffix = " \\" if index < len(digests) - 1 else ""
            lines.append("    --hash=sha256:" + digest + suffix)

    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
