#!/bin/sh
set -eu

command_line=${SSH_ORIGINAL_COMMAND:-status}

case "$command_line" in
  status)
    exec sudo -n /usr/local/sbin/muse-deploy status
    ;;
  rollback)
    exec sudo -n /usr/local/sbin/muse-deploy rollback
    ;;
  "deploy ghcr.io/haxurus/muse@sha256:"*)
    image=${command_line#deploy }
    digest=${image#ghcr.io/haxurus/muse@sha256:}
    [ "${#digest}" -eq 64 ] || exit 64
    case "$digest" in
      *[!0123456789abcdef]*) exit 64 ;;
    esac
    exec sudo -n /usr/local/sbin/muse-deploy deploy "$image"
    ;;
  *)
    echo "Unsupported deploy command." >&2
    exit 64
    ;;
esac
